import { CONTRACT_TYPE, CONTRACT_STATUS, PAYMENT_NODE } from './dict';

export const PaymentPlanOption = () => ({
  addBtn: true,
  delBtn: true,
  editBtn: true,
  column: [
    { label: '节点', prop: 'node', type: 'select', dicData: PAYMENT_NODE },
    { label: '比例(%)', prop: 'ratio', type: 'number', min: 0, max: 100 },
    { label: '金额', prop: 'amount', type: 'number', precision: 2 },
    { label: '计划日期', prop: 'planDate', type: 'date', valueFormat: 'YYYY-MM-DD' },
  ],
});

export const PaymentPlanDynamicColumn = () => ({
  label: '付款计划',
  prop: 'paymentPlans',
  type: 'dynamic',
  span: 24,
  hide: true,
  addDisplay: true,
  editDisplay: true,
  children: {
    align: 'center',
    headerAlign: 'center',
    column: PaymentPlanOption().column,
  },
});

export const Option = _this => ({
  border: true,
  index: true,
  viewBtn: false,
  addBtn: false,
  editBtn: false,
  dialogWidth: '85%',
  dialogClickModal: false,
  searchShow: true,
  searchSpan: 6,
  searchMenuSpan: 6,
  searchLabelWidth: 100,
  labelWidth: 120,
  overHidden: true,
  column: [
    { label: '合同编号', prop: 'code', addDisplay: false, editDisplay: false, search: true, minWidth: 130 },
    { label: '关联中标', prop: 'winbidCode', minWidth: 140, addDisplay: false, editDisplay: true, disabled: true },
    {
      label: '关联中标',
      prop: 'winbidId',
      type: 'select',
      filterable: true,
      hide: true,
      addDisplay: true,
      editDisplay: false,
      dicData: [],
      props: { label: 'name', value: 'id' },
      rules: [{ required: true, message: '请选择中标记录', trigger: 'change' }],
      change: ({ value }) => _this.onWinbidChange && _this.onWinbidChange(value),
    },
    {
      label: '客户名称',
      prop: 'customerName',
      search: true,
      minWidth: 160,
      addDisplay: true,
      editDisplay: true,
      disabled: true,
    },
    { label: '项目名称', prop: 'projectName', search: true, rules: [{ required: true, message: '必填', trigger: 'blur' }], minWidth: 180 },
    { label: '合同类型', prop: 'contractType', type: 'select', dicData: CONTRACT_TYPE, minWidth: 110 },
    { label: '合同金额', prop: 'contractAmount', type: 'number', precision: 2, rules: [{ required: true, message: '必填', trigger: 'blur' }], minWidth: 120 },
    { label: '服务周期起', prop: 'serviceStartDate', type: 'date', valueFormat: 'YYYY-MM-DD', hide: true },
    { label: '服务周期止', prop: 'serviceEndDate', type: 'date', valueFormat: 'YYYY-MM-DD', hide: true },
    { label: '签约时间', prop: 'signDate', type: 'date', valueFormat: 'YYYY-MM-DD', hide: true },
    { label: '合同状态', prop: 'contractStatus', type: 'select', dicData: CONTRACT_STATUS, search: true, minWidth: 100, addDisplay: false, editDisplay: false },
    { label: '服务内容', prop: 'serviceContent', type: 'textarea', span: 24, hide: true, minRows: 3 },
    PaymentPlanDynamicColumn(),
    {
      label: '合同附件',
      prop: 'contractFiles',
      span: 24,
      hide: true,
      formslot: true,
      addDisplay: true,
      editDisplay: true,
    },
    { label: '创建时间', prop: 'createTime', addDisplay: false, editDisplay: false, minWidth: 160 },
  ],
});
