import { CUSTOMER_TYPE, CUSTOMER_LEVEL, INDUSTRY, CUSTOMER_STATUS } from './dict';

export const Option = () => ({
  border: true,
  index: true,
  viewBtn: false,
  editBtn: true,
  delBtn: true,
  addBtn: true,
  selection: true,
  dialogWidth: '75%',
  dialogClickModal: false,
  searchSpan: 6,
  searchMenuSpan: 6,
  searchLabelWidth: 100,
  labelWidth: 120,
  overHidden: true,
  column: [
    { label: '客户编号', prop: 'code', addDisplay: false, editDisplay: false, search: true, minWidth: 130 },
    { label: '客户名称', prop: 'name', search: true, rules: [{ required: true, message: '请输入客户名称', trigger: 'blur' }], minWidth: 180 },
    { label: '客户类型', prop: 'customerType', type: 'select', dicData: CUSTOMER_TYPE, rules: [{ required: true, message: '请选择', trigger: 'change' }], minWidth: 100 },
    { label: '客户级别', prop: 'customerLevel', type: 'select', dicData: CUSTOMER_LEVEL, rules: [{ required: true, message: '请选择', trigger: 'change' }], minWidth: 100 },
    { label: '所属行业', prop: 'industry', type: 'select', dicData: INDUSTRY, minWidth: 90 },
    { label: '所属区域', prop: 'region', minWidth: 140 },
    { label: '详细地址', prop: 'address', hide: true, span: 24 },
    { label: '客户经理', prop: 'managerUserName', minWidth: 100 },
    { label: '纳税人识别号', prop: 'taxNo', hide: true },
    { label: '开户行', prop: 'bankName', hide: true },
    { label: '银行账号', prop: 'bankAccount', hide: true },
    { label: '客户状态', prop: 'status', type: 'select', dicData: CUSTOMER_STATUS, minWidth: 90, addDisplay: false, editDisplay: false },
    {
      label: '联系人',
      prop: 'contacts',
      type: 'dynamic',
      span: 24,
      hide: true,
      addDisplay: true,
      editDisplay: true,
      viewDisplay: false,
      children: {
        align: 'center',
        headerAlign: 'center',
        column: [
          { label: '姓名', prop: 'name', rules: [{ required: true, message: '必填', trigger: 'blur' }] },
          { label: '职务', prop: 'title' },
          { label: '电话', prop: 'phone', rules: [{ required: true, message: '必填', trigger: 'blur' }] },
          { label: '邮箱', prop: 'email' },
          {
            label: '主联系人',
            prop: 'isPrimary',
            type: 'select',
            dicData: [
              { label: '是', value: true },
              { label: '否', value: false },
            ],
            value: false,
          },
        ],
      },
    },
    { label: '创建时间', prop: 'createTime', addDisplay: false, editDisplay: false, minWidth: 160 },
  ],
});
