import { OPP_SOURCE, OPP_STAGE, OPP_STATUS, PROJECT_TYPE } from './dict';

export const Option = _this => ({
  border: true,
  index: true,
  viewBtn: false,
  addBtn: false,
  editBtn: false,
  dialogWidth: '80%',
  dialogClickModal: false,
  searchSpan: 6,
  searchMenuSpan: 6,
  searchLabelWidth: 100,
  labelWidth: 120,
  overHidden: true,
  column: [
    { label: '商机编号', prop: 'code', addDisplay: false, editDisplay: false, search: true, minWidth: 150 },
    { label: '客户名称', prop: 'customerName', search: true, minWidth: 160, addDisplay: false, editDisplay: false },
    {
      label: '客户名称',
      prop: 'customerId',
      type: 'select',
      filterable: true,
      hide: true,
      dicData: [],
      props: { label: 'name', value: 'id' },
      rules: [{ required: true, message: '请选择客户', trigger: 'change' }],
      change: ({ value }) => _this.onCustomerChange && _this.onCustomerChange(value),
    },
    { label: '项目名称', prop: 'projectName', search: true, rules: [{ required: true, message: '必填', trigger: 'blur' }], minWidth: 180 },
    { label: '商机来源', prop: 'source', type: 'select', dicData: OPP_SOURCE, minWidth: 110, rules: [{ required: true, message: '必填', trigger: 'change' }] },
    { label: '项目类型', prop: 'projectType', type: 'select', dicData: PROJECT_TYPE, minWidth: 110 },
    { label: '预计金额', prop: 'expectedAmount', type: 'number', min: 0, precision: 2, rules: [{ required: true, message: '必填', trigger: 'blur' }], minWidth: 120 },
    { label: '预计签约日', prop: 'expectedSignDate', type: 'date', valueFormat: 'YYYY-MM-DD', minWidth: 120 },
    { label: '登记阶段', prop: 'stage', type: 'select', dicData: OPP_STAGE, minWidth: 110 },
    { label: '跟进人', prop: 'followerName', minWidth: 100 },
    { label: '登记状态', prop: 'status', type: 'select', dicData: OPP_STATUS, search: true, minWidth: 100, addDisplay: false, editDisplay: false, viewDisplay: true },
    { label: '创建时间', prop: 'createTime', addDisplay: false, editDisplay: false, minWidth: 160 },
  ],
});
