import { TENDER_METHOD, TENDER_RESULT, WIN_CONTRACT_STATUS } from './dict';

export const Option = _this => ({
  border: true,
  index: true,
  viewBtn: false,
  addBtn: false,
  editBtn: false,
  dialogWidth: '80%',
  dialogClickModal: false,
  searchSpan: 6,
  searchMenuSpan: 6,
  searchLabelWidth: 110,
  labelWidth: 130,
  overHidden: true,
  column: [
    { label: '投标编号', prop: 'code', addDisplay: false, editDisplay: false, search: true, minWidth: 160 },
    { label: '关联商机', prop: 'opportunityName', minWidth: 160, addDisplay: false, editDisplay: false },
    {
      label: '关联商机',
      prop: 'opportunityId',
      type: 'select',
      filterable: true,
      hide: true,
      dicData: [],
      props: { label: 'name', value: 'id' },
      rules: [{ required: true, message: '请选择商机', trigger: 'change' }],
      change: ({ value }) => _this.onOppChange && _this.onOppChange(value),
    },
    { label: '项目名称', prop: 'projectName', search: true, rules: [{ required: true, message: '必填', trigger: 'blur' }], minWidth: 180 },
    { label: '招标单位', prop: 'tenderOrg', rules: [{ required: true, message: '必填', trigger: 'blur' }], minWidth: 160 },
    { label: '公告编号', prop: 'announcementNo', hide: true },
    { label: '招标方式', prop: 'tenderMethod', type: 'select', dicData: TENDER_METHOD, minWidth: 110, rules: [{ required: true, message: '必填', trigger: 'change' }] },
    { label: '投标报价', prop: 'bidAmount', type: 'number', precision: 2, rules: [{ required: true, message: '必填', trigger: 'blur' }], minWidth: 120 },
    { label: '投标保证金', prop: 'bidBond', type: 'number', precision: 2, hide: true },
    { label: '投标日期', prop: 'bidDate', type: 'date', valueFormat: 'YYYY-MM-DD', minWidth: 110, rules: [{ required: true, message: '必填', trigger: 'change' }] },
    { label: '开标时间', prop: 'openTime', type: 'datetime', valueFormat: 'YYYY-MM-DD HH:mm:ss', rules: [{ required: true, message: '必填', trigger: 'change' }], minWidth: 160 },
    {
      label: '中标结果',
      prop: 'result',
      type: 'select',
      dicData: TENDER_RESULT,
      search: true,
      minWidth: 100,
      addDisplay: true,
      editDisplay: false,
      viewDisplay: true,
    },
    { label: '中标金额', prop: 'winAmount', type: 'number', precision: 2, addDisplay: false, editDisplay: false, viewDisplay: false, hide: true },
    { label: '中标日期', prop: 'winDate', type: 'date', valueFormat: 'YYYY-MM-DD', addDisplay: false, editDisplay: false, viewDisplay: false, hide: true },
    { label: '通知书编号', prop: 'winNoticeNo', addDisplay: false, editDisplay: false, viewDisplay: false, hide: true },
    { label: '中标编号', prop: 'winbidCode', addDisplay: false, editDisplay: false, minWidth: 140 },
    { label: '合同状态', prop: 'contractStatus', type: 'select', dicData: WIN_CONTRACT_STATUS, addDisplay: false, editDisplay: false, minWidth: 110 },
    { label: '关联合同', prop: 'contractCode', addDisplay: false, editDisplay: false, minWidth: 130 },
    { label: '备注', prop: 'remark', type: 'textarea', span: 24, hide: true },
    {
      label: '投标文件',
      prop: 'bidFiles',
      span: 24,
      hide: true,
      formslot: true,
      addDisplay: true,
      editDisplay: true,
    },
    { label: '创建时间', prop: 'createTime', addDisplay: false, editDisplay: false, minWidth: 160 },
  ],
});
