import { WIN_CONTRACT_STATUS } from './dict';

export const Option = _this => ({
  border: true,
  index: true,
  viewBtn: false,
  editBtn: true,
  delBtn: true,
  addBtn: true,
  dialogWidth: '75%',
  dialogClickModal: false,
  searchSpan: 6,
  searchMenuSpan: 6,
  searchLabelWidth: 120,
  labelWidth: 130,
  overHidden: true,
  column: [
    { label: '中标编号', prop: 'code', addDisplay: false, editDisplay: false, search: true, minWidth: 150 },
    { label: '关联投标', prop: 'tenderCode', minWidth: 160, addDisplay: false, editDisplay: false },
    {
      label: '关联投标',
      prop: 'tenderId',
      type: 'select',
      filterable: true,
      hide: true,
      dicData: [],
      props: { label: 'name', value: 'id' },
      rules: [{ required: true, message: '请选择投标', trigger: 'change' }],
      change: ({ value }) => _this.onTenderChange && _this.onTenderChange(value),
    },
    { label: '项目名称', prop: 'projectName', search: true, addDisplay: false, editDisplay: false, minWidth: 180 },
    { label: '客户名称', prop: 'customerName', addDisplay: false, editDisplay: false, minWidth: 160 },
    { label: '通知书编号', prop: 'noticeNo', minWidth: 120, rules: [{ required: true, message: '必填', trigger: 'blur' }] },
    { label: '中标金额', prop: 'winAmount', type: 'number', precision: 2, minWidth: 120, rules: [{ required: true, message: '必填', trigger: 'blur' }] },
    { label: '中标日期', prop: 'winDate', type: 'date', valueFormat: 'YYYY-MM-DD', minWidth: 110, rules: [{ required: true, message: '必填', trigger: 'change' }] },
    { label: '服务期', prop: 'servicePeriod', hide: true },
    { label: '履约保证金', prop: 'performanceBond', type: 'number', precision: 2, hide: true },
    { label: '中标服务费', prop: 'serviceFee', type: 'number', precision: 2, hide: true },
    { label: '合同状态', prop: 'contractStatus', type: 'select', dicData: WIN_CONTRACT_STATUS, minWidth: 110, addDisplay: false, editDisplay: false },
    { label: '关联合同', prop: 'contractCode', minWidth: 130, addDisplay: false, editDisplay: false },
    {
      label: '中标通知书',
      prop: 'noticeFiles',
      span: 24,
      hide: true,
      formslot: true,
      addDisplay: true,
      editDisplay: true,
    },
    { label: '创建时间', prop: 'createTime', addDisplay: false, editDisplay: false, minWidth: 160 },
  ],
});
