import { CANDIDATE_SOURCE, CANDIDATE_STATUS } from './dict';

export const Option = () => ({
  border: true,
  index: true,
  viewBtn: false,
  editBtn: true,
  delBtn: true,
  addBtn: true,
  dialogType: 'drawer',
  dialogWidth: 860,
  dialogClickModal: false,
  searchSpan: 6,
  searchMenuSpan: 6,
  searchLabelWidth: 100,
  labelWidth: 110,
  overHidden: true,
  column: [
    { label: '候选编号', prop: 'code', addDisplay: false, editDisplay: false, search: true, minWidth: 140 },
    { label: '姓名', prop: 'name', search: true, rules: [{ required: true, message: '请输入姓名', trigger: 'blur' }], minWidth: 100 },
    { label: '岗位', prop: 'position', search: true, rules: [{ required: true, message: '请输入岗位', trigger: 'blur' }], minWidth: 150 },
    { label: '来源', prop: 'source', type: 'select', dicData: CANDIDATE_SOURCE, minWidth: 110 },
    { label: '状态', prop: 'status', type: 'select', dicData: CANDIDATE_STATUS, minWidth: 100, addDisplay: false, editDisplay: false },
    { label: '证书数', prop: 'certCount', addDisplay: false, editDisplay: false, minWidth: 80 },
    { label: '学历', prop: 'education', type: 'select', hide: true },
    { label: '工作年限', prop: 'experienceYears', type: 'number', hide: true },
    { label: '手机', prop: 'phone', hide: true },
    { label: '邮箱', prop: 'email', hide: true },
    { label: '简介', prop: 'summary', type: 'textarea', hide: true, span: 24, minRows: 2 },
    { label: '技能', prop: 'skillsText', hide: true, span: 24, placeholder: '逗号分隔' },
    { label: '项目经历', prop: 'projectCasesText', type: 'textarea', hide: true, span: 24, minRows: 4, placeholder: '每行填写一个项目经历' },
    { label: '资质证书', prop: 'certificateBindings', hide: true, span: 24, formslot: true, labelWidth: 0 },
    { label: '面试评分', prop: 'interviewScore', addDisplay: false, editDisplay: false, minWidth: 90 },
    { label: '简历', prop: 'resumeGenerated', addDisplay: false, editDisplay: false, minWidth: 80 },
    { label: '最近触达', prop: 'lastTouch', addDisplay: false, editDisplay: false, minWidth: 180 },
  ],
});
