export const Option = () => ({
  border: true,
  index: true,
  viewBtn: false,
  editBtn: true,
  delBtn: false,
  addBtn: false,
  dialogType: 'drawer',
  dialogWidth: 860,
  dialogClickModal: false,
  searchSpan: 6,
  searchMenuSpan: 6,
  searchLabelWidth: 100,
  labelWidth: 110,
  overHidden: true,
  column: [
    { label: '人才编号', prop: 'code', editDisplay: false, search: true, minWidth: 140 },
    { label: '姓名', prop: 'name', search: true, minWidth: 100 },
    { label: '岗位', prop: 'title', search: true, minWidth: 150 },
    { label: '部门', prop: 'deptName', search: true, minWidth: 130 },
    { label: '经验年限', prop: 'experienceYears', minWidth: 90 },
    { label: '证书数', prop: 'certCount', editDisplay: false, minWidth: 80 },
    { label: '简历命中', prop: 'resumeHits', editDisplay: false, minWidth: 90 },
    { label: '学历', prop: 'education', type: 'select', hide: true },
    { label: '手机', prop: 'phone', hide: true },
    { label: '邮箱', prop: 'email', hide: true },
    { label: '简介', prop: 'summary', type: 'textarea', hide: true, span: 24, minRows: 2 },
    { label: '项目经历', prop: 'projectCasesText', type: 'textarea', hide: true, span: 24, minRows: 4, placeholder: '每行填写一个项目经历' },
    { label: '技能', prop: 'skillsText', hide: true, span: 24, placeholder: '逗号分隔' },
    { label: '资质证书', prop: 'certificateBindings', hide: true, span: 24, formslot: true, labelWidth: 0 },
    { label: '入档时间', prop: 'createTime', editDisplay: false, minWidth: 160 },
  ],
});
